[package]
name = "llamassacre"
version = "0.1.0"
authors = ["rap2h <raphaelht@gmail.com>"]

[dependencies]
ggez = { version = "0.3", features = ["cargo-resource-root"] }
cgmath = "0.15.0"
rand = "0.3.16"